### PR TITLE
add some macros to help method wrapping

### PR DESCRIPTION
**Pull request by mp3butcher**
add some macros to help method wrapping
examplify with few osg::Group methods

kinda ugly but
It's working stuff I tested with lua script

### CODE REVIEW

**Comment by openscenegraph** [comment]
I understand the motivation behind these changes, but I don't think this particular incarnation of changes is the best we can do.

In the shader_pipeline branch I've solved part of the problem a bit better than is done in master but introducing ValueObject::set/getScalarValue() method.  It's probably time I cherry-picked these changes back into master.  This resolves part of the issue with getting index etc. parameters from lua scripts as it allows adaptation between doubles -> int/uint/float etc.  

I have yet provided the marco's to help the wrapping, or rolled it out widely across the various serializers.  The TextureCubeMap.cpp serializer is the one to look at in the shader_pipeline.  

I will have a think about the practicility of cherry picking stuff from the shader_pipeline mode.  I'm still officially on holiday so can't spend much time on this today... Back to work fulltime next week.

**Comment by openscenegraph** [comment]
I have now merged the ValueObject changes from shader_pipeline into master.  I will now have a look at merging the improvements to the lua plugin that are in the shader_pipeline branch too.

**Comment by openscenegraph** [comment]
I have checked into master some improvements to the lua plugin from the shader_pipeline branch.

**Comment by mp3butcher** [comment]
great! I'll test it

**Comment by openscenegraph** [comment]
There is a MatrixfUnfirom and MatrixdUniform in the shader_pipeline branch that subclasses from the osg::UniformBase if that's what you mean.  I don't think I've actually tested it - it's just a typedef and I've used the other variants.

The new osg::*Uniform types are easier to support with lua scripting, for a client project we ended up using the shader_pipeline branch simply because setting up a shader based scene graph was so much easier when using the new uniform types.  

Potentially the UniformBase class and it's new subclasses could be merged with master sooner than the while shader_pipeline branch, but it could break some end user code so I want to make sure I'm 100% happyu with the new UniformBase approach before merging this.

Over the next couple of months my plan is to complete the shader_pipeline work so might just concentrate on this and then merge.

Whether the shader_pipeline branch is suitable for you right now I can't say.  I've been merging master into shader_pipeline so it should be possible for you to at least keep access to the new classes that you've written that have been merged with master.

**Pull request closed without merging**
