### PR TITLE
Fix an issue with VAS

### PR DESCRIPTION
**Pull request by mp3butcher**
solving https://github.com/openscenegraph/OpenSceneGraph/issues/655
a test could be removed if we consider negligible the cost of calling glBindVertexArray(0) but i'm not so sure about that

### CODE REVIEW

**Comment by akortunov** [comment]
Unfortunately, in its current state this PR does not ifx the issue - I still get crashes with the same stack trace.

**Comment by mp3butcher** [comment]
I don't understand what you're doing.
When I reproduced your bug,  the game didn't even launch the intro....With this patch I played MW all the night in debug whitout any problem

**Comment by mp3butcher** [comment]
No I don't understand why it fails with you... I just check all my stuff and there's no mistake ...
Please try again

**Comment by robertosfield** [comment]
Thanks for looking into this @mp3butcher, I have done a first pass review of the changes and my initial response is that it looks like there is a bug lurking somewhere, it could be in the OSG, or it could be in 3rd party code.  From the changes I couldn't easily spot what the "bug" on the OSG that the changes are attempting to address.  If you've found a bug on the OSG could you point out the failure mechanism, or point me in the direction of an example that illustrates the bug.

**Comment by robertosfield** [comment]
I can't just merge random changes that may or may not fix and issue that
may or may not be a real problem in the OSG code base.  I need to be
understand what the actual bug is and how the changes address it,  This
particular set of changes doesn't feel coherent, it feels like a collection
of different hacks that somehow do something.  If you submitted these
changes before I rejected them it was probably for this reason.

Each time I have merged stuff with making sure it right is has come back to
bite us with bugs being introduced.  So it might fix things for the issue
you've seen, but it might just be masking a problem elsewhere.

Once I understand what is actually going wrong I'll be able to judge the
validity of fix, or come up with the most appropriate fix myself.

**Comment by mp3butcher** [comment]
These aren't random changes
If I haven't follow you on with some changes on VAS, there's a reason...I just can't remember.

**Comment by mp3butcher** [comment]
oups rolling back I can't reproduce the crash...!?
I don't know what happen I close the pr until i understand something

**Comment by robertosfield** [comment]
Thanks for perceiving with this issue.  Fingers crossed 3.6.3 is just fine.

**Pull request closed without merging**
