### PR TITLE
fix comment block CMake syntax

### PR DESCRIPTION
**Pull request by mp3butcher**
https://github.com/openscenegraph/OpenSceneGraph/issues/812

### CODE REVIEW

**Comment by DieSlower** [comment]
@mp3butcher  
Hi Julien,
Thanks for taking this on. 
The block comment needs to be replaced with #s
So each line between the block comments needs to have a leading # for this to work.

**Comment by mp3butcher** [comment]
no ... it was just a cmake block syntax

**Comment by DieSlower** [comment]
#FindFontconfig
#--------------

#Find Fontconfig headers and library.

#Imported Targets
#^^^^^^^^^^^^^^^^

#``Fontconfig::Fontconfig``
# The Fontconfig library, if found.

#Result Variables
#^^^^^^^^^^^^^^^^

#This will define the following variables in your project:

#``FONTCONFIG_FOUND``
#  true if (the requested version of) Fontconfig is available.
#``FONTCONFIG_VERSION``
#  the version of Fontconfig.
#``FONTCONFIG_LIBRARIES``
#  the libraries to link against to use Fontconfig.
#``FONTCONFIG_INCLUDE_DIRS``
#  where to find the Fontconfig headers.
#``FONTCONFIG_COMPILE_OPTIONS``
# this should be passed to target_compile_options(), if the
#target is not used for linking

**Comment by DieSlower** [comment]
@mp3butcher 
Hmm...Just tested the new comments
#[[=======================================================================.rst:
Text
=======================================================================]]
with RPMBuilder and getting the same error...

**Comment by mp3butcher** [comment]
@DieSlower  cmake version?

**Comment by DieSlower** [comment]
Actually, looks like we also had a problem with some code on our end that exposed this bug. 
But now that it's fixed, your change works. 

Thanks Julien!

**Comment by mp3butcher** [comment]
..so is this pr required?

**Comment by DieSlower** [comment]
Yes, with the fix that you created.

**Pull request merged**
