### PR TITLE
Adds glTF plugin

### PR DESCRIPTION
**Pull request by psi29a**
From AurL (Aurélien Chatelain) of Sketchfab (https://sketchfab.com/)

### Summary
Allows to read and convert a `.gltf` file with it's `.bin` file and images to an OSG scene. You will need to install or reference JPG and PNG libraries to OSG when building in order to get the textures paths included in output file.
(Note: it also supports `.osgb` files but embedded textures are not supported at the moment)

### Convert from glTF to OSG
The `osgconv` binary can be used for convert from glTF to OSG.
Example: `osgconv file.gltf output.osgt`

### Features supported
Supports all common glTF features including PBR materials (metallic/specular), animation, skin and morph. Spare accessors and more specific features are not supported.

### PBR Materials
PBR materials are not supported in OSG, so their parameters are added as metadata in the corresponding osg::StateSet.

Example of generated metadata:

**Texture metadata**

```
  osg::StringValueObject {
    UniqueID 28
    Name "sDiffuse"
    Value "1"
  }

  osg::StringValueObject {
    UniqueID 30
    Name "sMetallic"
    Value "7"
  }
```
**Factor metadata** VEC3 glTF factors are split into two different metadata `Color` and `Factor`. For diffuseFactor, it's split into `DiffuseFactor` which is the R of diffuseColor, `DiffuseColor` which is RGB and `OpacityFactor`

```
  osg::StringValueObject {
    UniqueID 16
    Name "DiffuseColor"
    Value "[1, 1, 1]"
  }

  osg::StringValueObject {
    UniqueID 19
    Name "EmissiveFactor"
    Value "0.7"
  }
  osg::StringValueObject {
    UniqueID 17
    Name "DiffuseFactor"
    Value "1"
  }
  osg::StringValueObject {
    UniqueID 20
    Name "MetallicFactor"
    Value "0.9"
  }
```
Other values correspond to the remaining values defined in glTF materials (`alphaMode`, `doubleSided` etc)

### CODE REVIEW

**Comment by 0871087123** [comment]
Expecting this very much.

**Comment by psi29a** [comment]
> Is this for glTF 1.0 or 2.0?

glTF 2.0

**Comment by openscenegraph** [comment]
Thanks for the submission.

I have just checked out the PR and attempted a compile under Kubuntu 18.04 with gcc 7.3.0 and get the following error:

100%] Building CXX object src/osgPlugins/gltf/CMakeFiles/osgdb_gltf.dir/ReaderWriterGLTF.cpp.o
In file included from /home/robert/OpenSceneGraph/src/osgPlugins/gltf/tiny_gltf.h:665:0,
                 from /home/robert/OpenSceneGraph/src/osgPlugins/gltf/GLTFReader:66,
                 from /home/robert/OpenSceneGraph/src/osgPlugins/gltf/ReaderWriterGLTF.cpp:27:
/home/robert/OpenSceneGraph/src/osgPlugins/gltf/./stb_image.h: In function ‘void stbi__build_fast_ac(stbi__int16*, stbi__huffman*)’:
/home/robert/OpenSceneGraph/src/osgPlugins/gltf/./stb_image.h:1580:36: error: left shift of negative value [-Werror=shift-negative-value]
             if (k < m) k += (-1 << magbits) + 1;
                                    ^~~~~~~
A quick scan through stl_image.h suggest it's public domain image loader, but the OSG already has far more capable image loading capabilities.  I doesn't make much sense to duplicate this and with it introduce extra maintenance burden.

A better way would be to just leverage the OSG's image plugin support.  It doesn't feel like this plugin is quite ready to be merged.

**Comment by jtorresfabra** [comment]
Hi all:

@psi29a Why are you sending this PR in the behalf of @AurL? First of all pinging him (using @) and asking for permission would be the right thing to do. Maybe he wants to do the PR himself when it is ready. I know you didn't do that, cause I work with him. This situation is really awkward. 

Second thing, @robertosfield: this code is not ready for submission, please forget and close this PR.

**Comment by openscenegraph** [comment]
Thanks for the info @jtorresfabra.  Will close this PR and await submission from @AurL.

**Comment by faerietree** [comment]
@AurL already put it forth before: https://github.com/openscenegraph/OpenSceneGraph/pull/519

@psi29a didn't mean any harm. We wanted to find the reason for why it was not a pull request candidate. It is a very desirable functionality and important to some projects.

Definitely excuses to @AurL for not contacting him beforehand. 🙈

**Pull request closed without merging**
