### PR TITLE
Submissions2

### PR DESCRIPTION
**Pull request by LaurensVoerman**
fixing a few problems found on checking the clone functions.

### CODE REVIEW

**Comment by openscenegraph** [comment]
Hi Laurens, 

I have just had a quick scan through the changes and I feel there are too wide ranging to be appropriate for a single pull request/merge.  It would be far better to have each commit mapped to a single pull request as then I can merge the uncontroversial parts and where appropriate kick off a discussion about the parts that have questions over them.

For now I'll leave the pull request here, but only for reference, I'm not planning on merging it.  Once we have the separated pull requests I'll work through them one by one.

**Comment by LaurensVoerman** [comment]
Hi Robbert,
I will create the seperate pull requests, but I'm still working out how git
works, so this will take a little time.
Regards, Laurens.

**Comment by LaurensVoerman** [comment]
Hi Robert,
I finished splitting this into separate pull requests, with one change in the new version:
not removing 

BasicAnimationManager::BasicAnimationManager(const AnimationManagerBase& b, const osg::CopyOp& copyop)

because it's used in OpenSceneGraph/examples/osganimationviewer/AnimtkViewer.cpp

I suppose this pull request can now be rejected or deleted or something.
Regards, Laurens.

**Comment by openscenegraph** [comment]
Thanks Laurens, I'll now close this pull request, record of it will still be on github so if you do need to double check something it'll still be accessible.

**Pull request closed without merging**
