### PR TITLE
Added FBO GL extensions (useful for mobile VR etc.)

### PR DESCRIPTION
**Pull request by valid-ptr**
(1) glFramebufferTexture2DMultisample
(2) glInvalidateFramebuffer

### CODE REVIEW

**Comment by openscenegraph** [comment]
If we are to merge this change with 3.6 then we'll need to update the SO version as the change affects the ABI.

This change might be best just merged with master.

**Comment by valid-ptr** [comment]
> If we are to merge this change with 3.6 then we'll need to update the SO version as the change affects the ABI.

Yes, but it does not change API, just improve it ;)

You decide :)

**Comment by openscenegraph** [comment]
On Fri, 13 Dec 2019 at 17:13, Konstantin S. Matveyev <
notifications@github.com> wrote:

> If we are to merge this change with 3.6 then we'll need to update the SO
> version as the change affects the ABI.
>
> Yes, but it does not change API, just improve it ;)
>
> You decide :)
>
The SO version is tied to the ABI, which will change, so it has to change.

If we are changing the SO version between 3.6.4 and 3.6.4 anyway then it'll
be OK to merge.  I haven't double checked this yet.

**Comment by valid-ptr** [comment]
**3.6.4** release => so version is **160**
**3.6.5** dev => so version is **161**

**Comment by openscenegraph** [comment]
On Mon, 16 Dec 2019 at 09:29, Konstantin S. Matveyev <
notifications@github.com> wrote:

> *3.6.4* release => so version is *160*
> *3.6.5* dev => so version is *161*
>
I looked it up and I updated the SO version number to 141 with fixes to
osgText. commit : 149c04b0df37e605a94495363801eb518b58a059

 So time to merge :-)

**Pull request merged**
