### PR TITLE
fix a bug in how vertexattributes are filled

### PR DESCRIPTION
**Pull request by mp3butcher**
That was it all along: 
a bug leading to bad  vertexattribute info in the shader

### CODE REVIEW

**Comment by openscenegraph** [comment]
Quick clarification, is this fix meant for master or the osganimation branch?

**Comment by mp3butcher** [comment]
it's a hotfix for master

**Comment by openscenegraph** [comment]
How much more work do you think would be required before osganimation branch would be considered for merging?

**Comment by mp3butcher** [comment]
I don't know it would require testing from the community.
The RigTransform new design differs a bit from the initial so i hope none will have problem with it

**Comment by mp3butcher** [comment]
@AurL @jtorresfabra @cedricpinson 
This bug concern also your osganimation version

**Pull request merged**
