### PR TITLE
add ComputeDispatch class

### PR DESCRIPTION
**Pull request by mp3butcher**
revoke glDispatch in PCProgram::useProgram
update example

remove numGroups both in Program and its serializer (@robertosfield  retrocompat not maintained)

### CODE REVIEW

**Comment by mp3butcher** [comment]
perhaps createVAS should be overiden in ComputeDispatch....

**Comment by openscenegraph** [comment]
I have done a first pass run through, mostly the changes look good. 

Breaking the backwards compatibility of serailizer isn't acceptable though so we'll need to come up with a fix. The way I would tackle this is to read dummy values and discard them, possible emitting a warning.  You can remove elements from serializer after specified versions. I'm happy to tackle this work.

**Comment by openscenegraph** [comment]
Hi Julian,

The ComputeDispatch PR is now merged, thanks for you efforts on this.  I've added back on serilalizer support for compute groups parameters to the Program serializer to retain backwards compatibility.  It would be worth you looking how I did it so you know how it's done in future.  The commit is:

https://github.com/openscenegraph/OpenSceneGraph/commit/c0a276e85023927cd056a28a028523ff709b8492#diff-b253cee269678a0c9d82052e07d0272c

**Comment by openscenegraph** [comment]
Dang, haven't done a before and after test w.r.t the SSBO warning yet...

**Comment by openscenegraph** [comment]
I just tested the OpenSceneGraph-3.4 branch and it has the same error.  I had to fix the shader file search paths in this branch to get as far a running with all the shaders so there is a fix checked into this branch for this.

With these fixes to finding the correct shaders I see exactly the same errors that your reported for the osgSSO example, it looks to me like the shaders are wrong.  Now looking into it.

**Comment by openscenegraph** [comment]
The GLSL errors in the osgSSO example are down to some vec3's being mixed in with float maths, it's buggy for sure.  I'm not the original author of this example or shader so I don't know what the intention is in the shaders.  Looking at the logs it was written by Marcus Hein back in 2014.

**Comment by openscenegraph** [comment]
I have hacked the SSO shaders a bit to avoid the mixing of types, I don't know the original intent behind the maths so likely took things away form the original intention but at least it compiles and runs cleanly.  An update to OpenScenGraph-Data is required to get this fix.

**Pull request merged**
