### PR TITLE
change the design of BufferIndexBinding to work with BufferData instead of BufferObject +matrix transpose

### PR DESCRIPTION
**Pull request by mp3butcher**
1) change the design of BufferIndexBinding to work with BufferData instead of BufferObject: it's more consistent with the rest of osg, allow user to bind bufferdata relative stuff, and further it allow serialization

2) add 2 methods: transpose (4x4 transpose) and transpose3x3 (orthogonal part of a mat4x4)

### CODE REVIEW

**Comment by openscenegraph** [comment]
What is the status of this PR w.r.t the MuiltiDrawIndirect branch?

Could you look at the error that Travis build has thrown up?

**Comment by mp3butcher** [comment]
100% compatible regarding MDI branch 
travis fail: I've missed a replacement in an example

**Comment by openscenegraph** [comment]
Should I merge with master or the MDI branch?

Is it time the MDI branch ready to merge with master?

**Comment by mp3butcher** [comment]
If you haven't any objection, all can be merge in master but I would remove DrawIndirectBufferBinding from BIB (in this pr i kept it to comply with master but in MDI I've already removed it)

**Comment by openscenegraph** [comment]
I have now merged this PR, if you generate a PR on the MDI branch I'll go ahead and merge it.  Fingers crossed everything will go smoothly.

**Comment by mp3butcher** [comment]
there's seam to be conflicts between MDI and master:/
should i merge with master then pr the branch then pr branch to master?

**Comment by openscenegraph** [comment]
Yes, first step would be to update MDI to master, get things working, check fixes in, then PR.

**Pull request merged**
