### PR TITLE
give the good camera to OcclusionQueryNode

### PR DESCRIPTION
**Pull request by mp3butcher**

### CODE REVIEW

**Comment by openscenegraph** [comment]
??  No clue why you've made this changes. seem pretty random and with no understandable explanation why you think it's appropriate.

FYI, CullVisitor::getCurrentCamera() is implementation as:

        inline osg::Camera* getCurrentCamera()
        {
            return getCurrentRenderStage()->getCamera();
        }

Which is what you substituted.  So  i am going to close this PR safe in the knowledge that it's pointless.

**Comment by mp3butcher** [comment]
oups i've made a mistake I wanted to write
getRenderStage()->getCamera()

**Comment by mp3butcher** [comment]
...taking current renderstage yields weird behavior with shadowcams

**Comment by mp3butcher** [comment]
...surely a bug in openmw shadow implementation...forget it

**Pull request closed without merging**
