### PR TITLE
add missing NVTT libraries to nvtt plugin linker

### PR DESCRIPTION
**Pull request by mp3butcher**
fix for https://github.com/openscenegraph/OpenSceneGraph/issues/434
doesn't work for debug configuration
I think it affects also master git
not 100% ok so may be wait till I mod FindNVTT.cmake

### CODE REVIEW

**Comment by openscenegraph** [comment]
I think the right way to handle this would be to change the FindNVTT.cmake to assemble all the libs that needed to be linked to into a single variable that the nvtt plugin uses.  This way if there are platform specific build dependencies then can be kept entirely in the FindNVTT.cmake.

**Comment by mp3butcher** [comment]
i'm currently doing it
ready in the pr in 5 min

**Comment by mp3butcher** [comment]
done

**Comment by mp3butcher** [comment]
heu do you have any idea why there are conflicts?

**Comment by mp3butcher** [comment]
I'll renew that... there's still problems

**Comment by mp3butcher** [comment]
mmh conan bug in fact

**Comment by mp3butcher** [comment]
mmh conan bug in fact

**Comment by mp3butcher** [comment]
heu do you have any idea why there are conflicts?

**Comment by mp3butcher** [comment]
arg debug and optimized are mixed

**Comment by mp3butcher** [comment]
now it's okay i think

**Comment by openscenegraph** [comment]
I merged the changes but unforunately they broke the Linux build so I've tweaked the changes to only require the new additional libs under Windows.  The commit is : ff1acce..1872103

I have checked these changes into OpenSceneGraph-3.4 and master.

Could you test these changes out.  Thanks,

**Comment by mp3butcher** [comment]
ok i relaunch conan but these changes seam not to change win32 behavior...

**Comment by mp3butcher** [comment]
MSVC14 win7 osg3.4.0 full build release OK

**Comment by mp3butcher** [comment]
Don't know if you have something to do with it but
Here's the recipe result built for osg34-MSVC14-Release-x64 (I use cracked tools so can't give any reliability guarantee about generated binaries) 
https://drive.google.com/file/d/1OFfrnU57hitFkMoHcMwMU0H0do-wf1qL/view?usp=sharing

**Pull request merged**
