### PR TITLE
Create.ccpp.yml

### PR DESCRIPTION
**Pull request by Rednickle**
update

### CODE REVIEW

**Comment by Rednickle** [comment]
update

**Comment by robertosfield** [comment]
When you generate a PR could you specify what the PR is for/what it includes not just the file you've created.

**Comment by Rednickle** [comment]
Hay why dont you go and build a data base...!!!!--Sent from my Android phone with GMX Mail. Please excuse my brevity.On 4/19/20, 10:49 PM Robert Osfield <notifications@github.com> wrote:

   
  When you generate a PR could you specify what the PR is for/what it includes not just the file you've created.

**Comment by robertosfield** [comment]
? Build a data base ?

I'm just asking you to communicate sufficiently clearly that we know what the work relates to so we don't have to go into the submission and work out what you might intend by your PR.  If there is conflict with other work, or elements that aren't yet complete we need to know this.

For instance we can CL already working for the OSG project here on github, just not using the new github Actions approach.  If we are to migrate across then that's a reasonable goal, but it'll need to include all the platforms that we already support and not loose any.

**Comment by openscenegraph** [comment]
I'm closing to PR without merging as it's duplicates the Travis CL support we already have but does so in an incomplete way so it's not yet in a state where it can replace the Travis CL support entirely.

**Pull request closed without merging**
