### PR TITLE
Sampler as Texture Property

### PR DESCRIPTION
**Pull request by mp3butcher**

### CODE REVIEW

**Comment by openscenegraph** [comment]
I have just done another quiick run though, I'm happier with how things are laid out now.  There is still the overlap between the sampler parameters in osg::Texture base class and the osg::Sampler.

Being able to attach a Sampler to osg::Texture is a good first step. I'm now wondering if the next natural step would be to have osg::Texture use osg::Sampler to store all the texture sampler parameters, and have all the osg::Texture sampler related property method set the sampler values.  This way you'd retain backwards compatibility and avoid issues with settings becoming inconsistent.  

Where GL4.2 samplers aren't available you'd still need to rely on the old texture sampler property settings, might it be possible to have osg::Sampler use the old methods in some way?

**Comment by mp3butcher** [comment]
after few  thinks I remember why I didn't put Sampler as Texture property in my previous PR:
It's not how samplers work:
A sampler is associated to a textureunit not to a textureobject !!!
with the design used here we can't use the same texture with differents samplers

**Comment by openscenegraph** [comment]
Thanks for explanation.  From the sound of it there is an implicit sampler for each texture object, and a sampler for each unit that uses the texture one if no other one is provided.  If this is how the GL driver implements things then I think the osg::Texture being able to use a Sampler to store it's sampler properties would still be fine.  It wouldn't preclude the osg::Sample being used independently.

**Comment by mp3butcher** [comment]
I can't tell there's a default sampler for each tu, my guess is more:
-if a sampler is bound to the tu it will be used
-otherwise classic sampleparams are used

**Pull request closed without merging**
